version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8015
    volumes:
      - .:/app
      - media:/app/media
    ports:
      - "8015:8015"
    depends_on:
      - postgres
    restart: always


volumes:
  media:
